name = "gcomposer"
main = "worker.js"
compatibility_date = "2026-04-01"

[[kv_namespaces]]
binding = "GCOM_SCRIPTS"
id = "1f7fdea060504215b6af409a1052788a"

[assets]
directory = "."
not_found_handling = "single-page-application"

[vars]
BUILD_SHA = "dev"
